#!/usr/bin/env bash
# Config to change the IP address of localhost and facebook.com in /etc/hosts

# Backup buena practica
sudo cp /etc/hosts /etc/hosts.bak
# Modificar localhost
sudo sed -i '/localhost/d' /etc/hosts
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null
# Modificar facebook.com
sudo sed -i '/facebook.com/d' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
# Display the changes to ensure the update is correct
echo "Updated /etc/hosts:"
cat /etc/hosts
